# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Collection

In [2]:
df = pd.read_csv("/content/Churn.csv")

In [3]:

pd.set_option('display.max_columns', None)

In [4]:
df.head()

,Customer ID,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,7590-VHVEA,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7044 entries, 0 to 7043
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        7044 non-null   object
 1   Gender             7044 non-null   object
 2   Senior Citizen     7044 non-null   int64
 3   Partner            7044 non-null   object
 4   Dependents         7044 non-null   object
 5   tenure             7044 non-null   int64
 6   Phone Service      7044 non-null   object
 7   Multiple Lines     7044 non-null   object
 8   Internet Service   7044 non-null   object
 9   Online Security    7044 non-null   object
 10  Online Backup      7044 non-null   object
 11  Device Protection  7044 non-null   object
 12  Tech Support       7044 non-null   object
 13  Streaming TV       7044 non-null   object
 14  Streaming Movies   7044 non-null   object
 15  Contract           7044 non-null   object
 16  Paperless Billing  7044 non-null   object
 17  Payment Method     7044 non-null   object
 18  Monthly Charges    7044 non-null   float64
 19  Total Charges      7044 non-null   object
 20  Churn              7044 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.shape

(7044, 21)

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer ID, Gender, Senior Citizen, Partner, Dependents, tenure, Phone Service, Multiple Lines, Internet Service, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Payment Method, Monthly Charges, Total Charges, Churn]
Index: []

In [9]:
df = df.drop_duplicates()

# Pre Processing

In [10]:
df.drop("Customer ID", axis = 1, inplace = True)

In [11]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [12]:
df.Gender.value_counts()

Gender
Male      3555
Female    3489
Name: count, dtype: int64

In [13]:
# a = {
#     "Male": 1,
#     "Female": 0
# }

df["Gender"] = df["Gender"].map({"Male": 1, "Female":0})

In [14]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,1,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,1,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [15]:
df["Senior Citizen"].value_counts()

Senior Citizen
0    5902
1    1142
Name: count, dtype: int64

In [16]:
df["Partner"].value_counts()

Partner
No     3641
Yes    3403
Name: count, dtype: int64

In [17]:
df["Partner"] = df["Partner"].map({"Yes": 1, "No": 0})

In [18]:
df["tenure"].value_counts()

tenure
1     614
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

In [19]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,0,0,1,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,0,1,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,1,0,0,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,1,0,0,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,1,0,0,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [20]:
df['Dependents'].value_counts()

Dependents
No     4934
Yes    2110
Name: count, dtype: int64

In [21]:
df["Dependents"] = df["Dependents"].map({"Yes": 1, "No": 0})

In [22]:
df["Phone Service"].value_counts()

Phone Service
Yes    6361
No      683
Name: count, dtype: int64

In [23]:
df["Phone Service"] = df["Phone Service"].map({"Yes": 1, "No": 0})

In [24]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [25]:
df["Multiple Lines"].value_counts()

Multiple Lines
No                  3390
Yes                 2971
No phone service     683
Name: count, dtype: int64

In [26]:
df["Multiple Lines"] = df["Multiple Lines"].map({"Yes": 1, "No": 0, "No phone service": 0})

In [27]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,0,0,1,0,1,0,0,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,0,1,0,1,0,0,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,1,0,0,0,34,1,0,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,1,0,0,0,2,1,0,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,1,0,0,0,45,0,0,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No

In [28]:
df.shape

(7044, 20)

In [29]:
df["Internet Service"].value_counts()

Internet Service
Fiber optic    3096
DSL            2422
No             1526
Name: count, dtype: int64

In [30]:
df = pd.get_dummies(df, columns=["Internet Service"])

In [31]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No
0,0,0,1,0,1,0,0,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False,False
1,0,0,1,0,1,0,0,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False,False
2,1,0,0,0,34,1,0,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No,True,False,False
3,1,0,0,0,2,1,0,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,True,False,False
4,1,0,0,0,45,0,0,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,True,False,False

In [32]:
df["Online Security"].value_counts()

Online Security
No                     3499
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [33]:
df["Online Backup"].value_counts()

Online Backup
No                     3088
Yes                    2430
No internet service    1526
Name: count, dtype: int64

In [34]:
df["Device Protection"].value_counts()

Device Protection
No                     3096
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [35]:
df = pd.get_dummies(df, columns=["Online Security", "Online Backup", "Device Protection"])

In [36]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes
0,0,0,1,0,1,0,0,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False
1,0,0,1,0,1,0,0,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False
2,1,0,0,0,34,1,0,No,No,No,One year,No,Mailed check,56.95,1889.5,No,True,False,False,False,False,True,True,False,False,False,False,True
3,1,0,0,0,2,1,0,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,True,False,False,False,False,True,False,False,True,True,False,False
4,1,0,0,0,45,0,0,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,True,False,False,False,False,True,True,False,False,False,False,True

In [37]:
df.columns.to_list()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'tenure',
 'Phone Service',
 'Multiple Lines',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn',
 'Internet Service_DSL',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Online Security_No',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No',
 'Device Protection_No internet service',
 'Device Protection_Yes']

In [38]:
df["Tech Support"].value_counts()

Tech Support
No                     3474
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [39]:
df["Streaming TV"].value_counts()

Streaming TV
No                     2811
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [40]:
df["Streaming Movies"].value_counts()

Streaming Movies
No                     2786
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [41]:
df = pd.get_dummies(df, columns=["Tech Support", "Streaming TV", "Streaming Movies"])

In [42]:
df.columns.to_list()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'tenure',
 'Phone Service',
 'Multiple Lines',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn',
 'Internet Service_DSL',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Online Security_No',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No',
 'Device Protection_No internet service',
 'Device Protection_Yes',
 'Tech Support_No',
 'Tech Support_No internet service',
 'Tech Support_Yes',
 'Streaming TV_No',
 'Streaming TV_No internet service',
 'Streaming TV_Yes',
 'Streaming Movies_No',
 'Streaming Movies_No internet service',
 'Streaming Movies_Yes']

In [43]:
df["Contract"].value_counts()

Contract
Month-to-month    3876
Two year          1695
One year          1473
Name: count, dtype: int64

In [44]:
df = pd.get_dummies(df, columns= ["Contract"])

In [45]:
df["Paperless Billing"].value_counts()

Paperless Billing
Yes    4172
No     2872
Name: count, dtype: int64

In [46]:
df["Paperless Billing"] = df["Paperless Billing"].map({
    'Yes': 1,
    'No': 0
})

In [47]:
df["Payment Method"].value_counts()

Payment Method
Electronic check             2366
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [48]:
df = pd.get_dummies(df, columns= ["Payment Method"])

In [49]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
1,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
2,1,0,0,0,34,1,0,0,56.95,1889.5,No,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True
3,1,0,0,0,2,1,0,1,53.85,108.15,Yes,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,True
4,1,0,0,0,45,0,0,0,42.30,1840.75,No,True,False,False,False,False,True,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,False,True,False,True,False,False,False

In [50]:
df.columns.to_list()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'tenure',
 'Phone Service',
 'Multiple Lines',
 'Paperless Billing',
 'Monthly Charges',
 'Total Charges',
 'Churn',
 'Internet Service_DSL',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Online Security_No',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No',
 'Device Protection_No internet service',
 'Device Protection_Yes',
 'Tech Support_No',
 'Tech Support_No internet service',
 'Tech Support_Yes',
 'Streaming TV_No',
 'Streaming TV_No internet service',
 'Streaming TV_Yes',
 'Streaming Movies_No',
 'Streaming Movies_No internet service',
 'Streaming Movies_Yes',
 'Contract_Month-to-month',
 'Contract_One year',
 'Contract_Two year',
 'Payment Method_Bank transfer (automatic)',
 'Payment Method_Credit card (automatic)',
 'Payment Method_Electronic check',
 'Payment Method_Mailed check']

In [51]:
df["Monthly Charges"].value_counts()

Monthly Charges
20.05    61
19.85    45
19.95    44
19.90    44
19.65    43
         ..
92.05     1
63.30     1
99.60     1
63.75     1
92.35     1
Name: count, Length: 1585, dtype: int64

In [52]:
df["Total Charges"].value_counts()

Total Charges
           11
20.2       11
19.75       9
19.9        8
19.65       8
           ..
130.15      1
3211.9      1
7843.55     1
2196.3      1
197.4       1
Name: count, Length: 6531, dtype: int64

In [53]:
df.isnull().sum()

Gender                                      0
Senior Citizen                              0
Partner                                     0
Dependents                                  0
tenure                                      0
Phone Service                               0
Multiple Lines                              0
Paperless Billing                           0
Monthly Charges                             0
Total Charges                               0
Churn                                       0
Internet Service_DSL                        0
Internet Service_Fiber optic                0
Internet Service_No                         0
Online Security_No                          0
Online Security_No internet service         0
Online Security_Yes                         0
Online Backup_No                            0
Online Backup_No internet service           0
Online Backup_Yes                           0
Device Protection_No                        0
Device Protection_No internet service       0
Device Protection_Yes                       0
Tech Support_No                             0
Tech Support_No internet service            0
Tech Support_Yes                            0
Streaming TV_No                             0
Streaming TV_No internet service            0
Streaming TV_Yes                            0
Streaming Movies_No                         0
Streaming Movies_No internet service        0
Streaming Movies_Yes                        0
Contract_Month-to-month                     0
Contract_One year                           0
Contract_Two year                           0
Payment Method_Bank transfer (automatic)    0
Payment Method_Credit card (automatic)      0
Payment Method_Electronic check             0
Payment Method_Mailed check                 0
dtype: int64

In [54]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
1,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
2,1,0,0,0,34,1,0,0,56.95,1889.5,No,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True
3,1,0,0,0,2,1,0,1,53.85,108.15,Yes,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,True
4,1,0,0,0,45,0,0,0,42.30,1840.75,No,True,False,False,False,False,True,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,False,True,False,True,False,False,False

In [55]:
df["Total Charges"].value_counts()

Total Charges
           11
20.2       11
19.75       9
19.9        8
19.65       8
           ..
130.15      1
3211.9      1
7843.55     1
2196.3      1
197.4       1
Name: count, Length: 6531, dtype: int64

In [56]:
df["Churn"].value_counts()

Churn
No     5175
Yes    1869
Name: count, dtype: int64

In [57]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
1,0,0,1,0,1,0,0,1,29.85,29.85,No,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,True,False
2,1,0,0,0,34,1,0,0,56.95,1889.5,No,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True
3,1,0,0,0,2,1,0,1,53.85,108.15,Yes,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,True
4,1,0,0,0,45,0,0,0,42.30,1840.75,No,True,False,False,False,False,True,True,False,False,False,False,True,False,False,True,True,False,False,True,False,False,False,True,False,True,False,False,False

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7044 entries, 0 to 7043
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7044 non-null   int64
 1   Senior Citizen                            7044 non-null   int64
 2   Partner                                   7044 non-null   int64
 3   Dependents                                7044 non-null   int64
 4   tenure                                    7044 non-null   int64
 5   Phone Service                             7044 non-null   int64
 6   Multiple Lines                            7044 non-null   int64
 7   Paperless Billing                         7044 non-null   int64
 8   Monthly Charges                           7044 non-null   float64
 9   Total Charges                             7044 non-null   object
 10  Churn                                     7044 non-null   object
 11  Internet Service_DSL                      7044 non-null   bool
 12  Internet Service_Fiber optic              7044 non-null   bool
 13  Internet Service_No                       7044 non-null   bool
 14  Online Security_No                        7044 non-null   bool
 15  Online Security_No internet service       7044 non-null   bool
 16  Online Security_Yes                       7044 non-null   bool
 17  Online Backup_No                          7044 non-null   bool
 18  Online Backup_No internet service         7044 non-null   bool
 19  Online Backup_Yes                         7044 non-null   bool
 20  Device Protection_No                      7044 non-null   bool
 21  Device Protection_No internet service     7044 non-null   bool
 22  Device Protection_Yes                     7044 non-null   bool
 23  Tech Support_No                           7044 non-null   bool
 24  Tech Support_No internet service          7044 non-null   bool
 25  Tech Support_Yes                          7044 non-null   bool
 26  Streaming TV_No                           7044 non-null   bool
 27  Streaming TV_No internet service          7044 non-null   bool
 28  Streaming TV_Yes                          7044 non-null   bool
 29  Streaming Movies_No                       7044 non-null   bool
 30  Streaming Movies_No internet service      7044 non-null   bool
 31  Streaming Movies_Yes                      7044 non-null   bool
 32  Contract_Month-to-month                   7044 non-null   bool
 33  Contract_One year                         7044 non-null   bool
 34  Contract_Two year                         7044 non-null   bool
 35  Payment Method_Bank transfer (automatic)  7044 non-null   bool
 36  Payment Method_Credit card (automatic)    7044 non-null   bool
 37  Payment Method_Electronic check           7044 non-null   bool
 38  Payment Method_Mailed check               7044 non-null   bool
dtypes: bool(28), float64(1), int64(8), object(2)
memory usage: 798.1+ KB

In [59]:
bool_col = [
    "Internet Service_DSL",
    "Internet Service_Fiber optic",
    "Internet Service_No",
    "Online Security_No",
    "Online Security_No internet service",
    "Online Security_Yes",
    "Online Backup_No",
    "Online Backup_No internet service",
    "Online Backup_Yes",
    "Device Protection_No",
    "Device Protection_No internet service",
    "Device Protection_Yes",
    "Tech Support_No",
    "Tech Support_No internet service",
    "Tech Support_Yes",
    "Streaming TV_No",
    "Streaming TV_No internet service",
    "Streaming TV_Yes",
    "Streaming Movies_No",
    "Streaming Movies_No internet service",
    "Streaming Movies_Yes",
    "Contract_Month-to-month",
    "Contract_One year",
    "Contract_Two year",
    "Payment Method_Bank transfer (automatic)",
    "Payment Method_Credit card (automatic)",
    "Payment Method_Electronic check",
    "Payment Method_Mailed check"
]

In [60]:
df[bool_col] = df[bool_col].astype(int)

In [61]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,No,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
1,0,0,1,0,1,0,0,1,29.85,29.85,No,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
2,1,0,0,0,34,1,0,0,56.95,1889.5,No,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
3,1,0,0,0,2,1,0,1,53.85,108.15,Yes,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
4,1,0,0,0,45,0,0,0,42.30,1840.75,No,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0,0

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7044 entries, 0 to 7043
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7044 non-null   int64
 1   Senior Citizen                            7044 non-null   int64
 2   Partner                                   7044 non-null   int64
 3   Dependents                                7044 non-null   int64
 4   tenure                                    7044 non-null   int64
 5   Phone Service                             7044 non-null   int64
 6   Multiple Lines                            7044 non-null   int64
 7   Paperless Billing                         7044 non-null   int64
 8   Monthly Charges                           7044 non-null   float64
 9   Total Charges                             7044 non-null   object
 10  Churn                                     7044 non-null   object
 11  Internet Service_DSL                      7044 non-null   int64
 12  Internet Service_Fiber optic              7044 non-null   int64
 13  Internet Service_No                       7044 non-null   int64
 14  Online Security_No                        7044 non-null   int64
 15  Online Security_No internet service       7044 non-null   int64
 16  Online Security_Yes                       7044 non-null   int64
 17  Online Backup_No                          7044 non-null   int64
 18  Online Backup_No internet service         7044 non-null   int64
 19  Online Backup_Yes                         7044 non-null   int64
 20  Device Protection_No                      7044 non-null   int64
 21  Device Protection_No internet service     7044 non-null   int64
 22  Device Protection_Yes                     7044 non-null   int64
 23  Tech Support_No                           7044 non-null   int64
 24  Tech Support_No internet service          7044 non-null   int64
 25  Tech Support_Yes                          7044 non-null   int64
 26  Streaming TV_No                           7044 non-null   int64
 27  Streaming TV_No internet service          7044 non-null   int64
 28  Streaming TV_Yes                          7044 non-null   int64
 29  Streaming Movies_No                       7044 non-null   int64
 30  Streaming Movies_No internet service      7044 non-null   int64
 31  Streaming Movies_Yes                      7044 non-null   int64
 32  Contract_Month-to-month                   7044 non-null   int64
 33  Contract_One year                         7044 non-null   int64
 34  Contract_Two year                         7044 non-null   int64
 35  Payment Method_Bank transfer (automatic)  7044 non-null   int64
 36  Payment Method_Credit card (automatic)    7044 non-null   int64
 37  Payment Method_Electronic check           7044 non-null   int64
 38  Payment Method_Mailed check               7044 non-null   int64
dtypes: float64(1), int64(36), object(2)
memory usage: 2.1+ MB

In [63]:
df.isnull().sum()

Gender                                      0
Senior Citizen                              0
Partner                                     0
Dependents                                  0
tenure                                      0
Phone Service                               0
Multiple Lines                              0
Paperless Billing                           0
Monthly Charges                             0
Total Charges                               0
Churn                                       0
Internet Service_DSL                        0
Internet Service_Fiber optic                0
Internet Service_No                         0
Online Security_No                          0
Online Security_No internet service         0
Online Security_Yes                         0
Online Backup_No                            0
Online Backup_No internet service           0
Online Backup_Yes                           0
Device Protection_No                        0
Device Protection_No internet service       0
Device Protection_Yes                       0
Tech Support_No                             0
Tech Support_No internet service            0
Tech Support_Yes                            0
Streaming TV_No                             0
Streaming TV_No internet service            0
Streaming TV_Yes                            0
Streaming Movies_No                         0
Streaming Movies_No internet service        0
Streaming Movies_Yes                        0
Contract_Month-to-month                     0
Contract_One year                           0
Contract_Two year                           0
Payment Method_Bank transfer (automatic)    0
Payment Method_Credit card (automatic)      0
Payment Method_Electronic check             0
Payment Method_Mailed check                 0
dtype: int64

In [64]:
df.dtypes

Gender                                        int64
Senior Citizen                                int64
Partner                                       int64
Dependents                                    int64
tenure                                        int64
Phone Service                                 int64
Multiple Lines                                int64
Paperless Billing                             int64
Monthly Charges                             float64
Total Charges                                object
Churn                                        object
Internet Service_DSL                          int64
Internet Service_Fiber optic                  int64
Internet Service_No                           int64
Online Security_No                            int64
Online Security_No internet service           int64
Online Security_Yes                           int64
Online Backup_No                              int64
Online Backup_No internet service             int64
Online Backup_Yes                             int64
Device Protection_No                          int64
Device Protection_No internet service         int64
Device Protection_Yes                         int64
Tech Support_No                               int64
Tech Support_No internet service              int64
Tech Support_Yes                              int64
Streaming TV_No                               int64
Streaming TV_No internet service              int64
Streaming TV_Yes                              int64
Streaming Movies_No                           int64
Streaming Movies_No internet service          int64
Streaming Movies_Yes                          int64
Contract_Month-to-month                       int64
Contract_One year                             int64
Contract_Two year                             int64
Payment Method_Bank transfer (automatic)      int64
Payment Method_Credit card (automatic)        int64
Payment Method_Electronic check               int64
Payment Method_Mailed check                   int64
dtype: object

In [65]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors='coerce')

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7044 entries, 0 to 7043
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7044 non-null   int64
 1   Senior Citizen                            7044 non-null   int64
 2   Partner                                   7044 non-null   int64
 3   Dependents                                7044 non-null   int64
 4   tenure                                    7044 non-null   int64
 5   Phone Service                             7044 non-null   int64
 6   Multiple Lines                            7044 non-null   int64
 7   Paperless Billing                         7044 non-null   int64
 8   Monthly Charges                           7044 non-null   float64
 9   Total Charges                             7033 non-null   float64
 10  Churn                                     7044 non-null   object
 11  Internet Service_DSL                      7044 non-null   int64
 12  Internet Service_Fiber optic              7044 non-null   int64
 13  Internet Service_No                       7044 non-null   int64
 14  Online Security_No                        7044 non-null   int64
 15  Online Security_No internet service       7044 non-null   int64
 16  Online Security_Yes                       7044 non-null   int64
 17  Online Backup_No                          7044 non-null   int64
 18  Online Backup_No internet service         7044 non-null   int64
 19  Online Backup_Yes                         7044 non-null   int64
 20  Device Protection_No                      7044 non-null   int64
 21  Device Protection_No internet service     7044 non-null   int64
 22  Device Protection_Yes                     7044 non-null   int64
 23  Tech Support_No                           7044 non-null   int64
 24  Tech Support_No internet service          7044 non-null   int64
 25  Tech Support_Yes                          7044 non-null   int64
 26  Streaming TV_No                           7044 non-null   int64
 27  Streaming TV_No internet service          7044 non-null   int64
 28  Streaming TV_Yes                          7044 non-null   int64
 29  Streaming Movies_No                       7044 non-null   int64
 30  Streaming Movies_No internet service      7044 non-null   int64
 31  Streaming Movies_Yes                      7044 non-null   int64
 32  Contract_Month-to-month                   7044 non-null   int64
 33  Contract_One year                         7044 non-null   int64
 34  Contract_Two year                         7044 non-null   int64
 35  Payment Method_Bank transfer (automatic)  7044 non-null   int64
 36  Payment Method_Credit card (automatic)    7044 non-null   int64
 37  Payment Method_Electronic check           7044 non-null   int64
 38  Payment Method_Mailed check               7044 non-null   int64
dtypes: float64(2), int64(36), object(1)
memory usage: 2.1+ MB

In [67]:
df["Total Charges"].isnull().sum()

np.int64(11)

In [68]:
df = df.dropna(subset=["Total Charges"])

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7033 entries, 0 to 7043
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7033 non-null   int64
 1   Senior Citizen                            7033 non-null   int64
 2   Partner                                   7033 non-null   int64
 3   Dependents                                7033 non-null   int64
 4   tenure                                    7033 non-null   int64
 5   Phone Service                             7033 non-null   int64
 6   Multiple Lines                            7033 non-null   int64
 7   Paperless Billing                         7033 non-null   int64
 8   Monthly Charges                           7033 non-null   float64
 9   Total Charges                             7033 non-null   float64
 10  Churn                                     7033 non-null   object
 11  Internet Service_DSL                      7033 non-null   int64
 12  Internet Service_Fiber optic              7033 non-null   int64
 13  Internet Service_No                       7033 non-null   int64
 14  Online Security_No                        7033 non-null   int64
 15  Online Security_No internet service       7033 non-null   int64
 16  Online Security_Yes                       7033 non-null   int64
 17  Online Backup_No                          7033 non-null   int64
 18  Online Backup_No internet service         7033 non-null   int64
 19  Online Backup_Yes                         7033 non-null   int64
 20  Device Protection_No                      7033 non-null   int64
 21  Device Protection_No internet service     7033 non-null   int64
 22  Device Protection_Yes                     7033 non-null   int64
 23  Tech Support_No                           7033 non-null   int64
 24  Tech Support_No internet service          7033 non-null   int64
 25  Tech Support_Yes                          7033 non-null   int64
 26  Streaming TV_No                           7033 non-null   int64
 27  Streaming TV_No internet service          7033 non-null   int64
 28  Streaming TV_Yes                          7033 non-null   int64
 29  Streaming Movies_No                       7033 non-null   int64
 30  Streaming Movies_No internet service      7033 non-null   int64
 31  Streaming Movies_Yes                      7033 non-null   int64
 32  Contract_Month-to-month                   7033 non-null   int64
 33  Contract_One year                         7033 non-null   int64
 34  Contract_Two year                         7033 non-null   int64
 35  Payment Method_Bank transfer (automatic)  7033 non-null   int64
 36  Payment Method_Credit card (automatic)    7033 non-null   int64
 37  Payment Method_Electronic check           7033 non-null   int64
 38  Payment Method_Mailed check               7033 non-null   int64
dtypes: float64(2), int64(36), object(1)
memory usage: 2.1+ MB

In [70]:
df["Churn"].value_counts()

Churn
No     5164
Yes    1869
Name: count, dtype: int64

In [71]:
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

In [72]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
1,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
2,1,0,0,0,34,1,0,0,56.95,1889.50,0,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
3,1,0,0,0,2,1,0,1,53.85,108.15,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
4,1,0,0,0,45,0,0,0,42.30,1840.75,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0,0

In [73]:
df["Churn"].unique()

array([0, 1])

In [74]:
df["Churn"] = df["Churn"].astype(int)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7033 entries, 0 to 7043
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender                                    7033 non-null   int64
 1   Senior Citizen                            7033 non-null   int64
 2   Partner                                   7033 non-null   int64
 3   Dependents                                7033 non-null   int64
 4   tenure                                    7033 non-null   int64
 5   Phone Service                             7033 non-null   int64
 6   Multiple Lines                            7033 non-null   int64
 7   Paperless Billing                         7033 non-null   int64
 8   Monthly Charges                           7033 non-null   float64
 9   Total Charges                             7033 non-null   float64
 10  Churn                                     7033 non-null   int64
 11  Internet Service_DSL                      7033 non-null   int64
 12  Internet Service_Fiber optic              7033 non-null   int64
 13  Internet Service_No                       7033 non-null   int64
 14  Online Security_No                        7033 non-null   int64
 15  Online Security_No internet service       7033 non-null   int64
 16  Online Security_Yes                       7033 non-null   int64
 17  Online Backup_No                          7033 non-null   int64
 18  Online Backup_No internet service         7033 non-null   int64
 19  Online Backup_Yes                         7033 non-null   int64
 20  Device Protection_No                      7033 non-null   int64
 21  Device Protection_No internet service     7033 non-null   int64
 22  Device Protection_Yes                     7033 non-null   int64
 23  Tech Support_No                           7033 non-null   int64
 24  Tech Support_No internet service          7033 non-null   int64
 25  Tech Support_Yes                          7033 non-null   int64
 26  Streaming TV_No                           7033 non-null   int64
 27  Streaming TV_No internet service          7033 non-null   int64
 28  Streaming TV_Yes                          7033 non-null   int64
 29  Streaming Movies_No                       7033 non-null   int64
 30  Streaming Movies_No internet service      7033 non-null   int64
 31  Streaming Movies_Yes                      7033 non-null   int64
 32  Contract_Month-to-month                   7033 non-null   int64
 33  Contract_One year                         7033 non-null   int64
 34  Contract_Two year                         7033 non-null   int64
 35  Payment Method_Bank transfer (automatic)  7033 non-null   int64
 36  Payment Method_Credit card (automatic)    7033 non-null   int64
 37  Payment Method_Electronic check           7033 non-null   int64
 38  Payment Method_Mailed check               7033 non-null   int64
dtypes: float64(2), int64(37)
memory usage: 2.1 MB

In [76]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
1,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
2,1,0,0,0,34,1,0,0,56.95,1889.50,0,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
3,1,0,0,0,2,1,0,1,53.85,108.15,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
4,1,0,0,0,45,0,0,0,42.30,1840.75,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0,0

# Data Splitting

In [77]:
x = df.drop("Churn", axis = 1)
y = df["Churn"]

In [78]:
k = x.columns.to_list()

In [79]:
if "Churn" in k:
  print("Yes")
else:
  print("No")

No

In [80]:
y.head()

0    0
1    0
2    0
3    1
4    0
Name: Churn, dtype: int64

# Train Test Split

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [83]:
x_train.shape

(5626, 38)

In [84]:
y_train.shape

(5626,)

In [85]:
x_test.shape

(1407, 38)

In [86]:
y_test.shape

(1407,)

# Model Training

In [87]:
from sklearn.linear_model import LogisticRegression

In [88]:
lr = LogisticRegression()

lr.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [89]:
lr.score(x_test, y_test)

0.7882018479033405

In [90]:
lr.score(x_train, y_train)

0.8059011731247778

In [91]:
from sklearn.ensemble import RandomForestClassifier
model_rfc = RandomForestClassifier()

In [92]:
model_rfc.fit(x_train, y_train)

RandomForestClassifier()

In [93]:
model_rfc.score(x_test, y_test)

0.7818052594171997

In [94]:
model_rfc.score(x_train, y_train)

0.9982225382154284

In [95]:
param_grid = {
              "n_estimators" : [200, 300, 400, 500, 600, 700, 800, 1000],
              "max_depth": [4, 5, 6, 7, 8, 9, 10, 12],
              "min_samples_leaf": range(2, 11),
              "min_samples_split": [2, 4, 5, 6, 8, 9, 10],
              # "max_leaf_nodes": range(4, 23),
              "max_features": range(3,8)
}

In [96]:
param_grid1 = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 15],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt"]
}

In [97]:
from sklearn.model_selection import RandomizedSearchCV

In [98]:
hyper_rfc = RandomizedSearchCV(RandomForestClassifier(random_state=42), param_distributions = param_grid1, random_state=42)
hyper_rfc.fit(x_train, y_train)

RandomizedSearchCV(estimator=RandomForestClassifier(random_state=42),
                   param_distributions={'max_depth': [None, 10, 15],
                                        'max_features': ['sqrt'],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [100, 200]},
                   random_state=42)

In [99]:
hyper_rfc.score(x_train, y_train)

0.8602915037326697

In [100]:
hyper_rfc.score(x_test, y_test)

0.7931769722814499

In [101]:
hyper_rfc.best_params_

{'n_estimators': 200,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 10}

In [102]:
model_rf = RandomForestClassifier(
    n_estimators = 200,
    min_samples_split = 2,
    min_samples_leaf = 2,
    max_features  = 'sqrt',
    max_depth = 10
)
model_rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, n_estimators=200)

In [103]:
model_rf.score(x_train, y_train)

0.8611802346249555

In [104]:
model_rf.score(x_test, y_test)

0.7960199004975125

In [105]:
y_pred_train = model_rf.predict(x_train)
y_pred_test = model_rf.predict(x_test)

Accuracy -- Measures overall correctness

Confusion Matrix -- True Positive (TP), False Positive (FP), True Negative (TN), False Negative (FN).

Classification Report -- Precision, Recall, F1-score, Support.

Precision -- Out of predicted positives, how many are correct

Recall -- Out of actual positives, how many you captured

F1 Score -- Balance between precision & recall

In [106]:
# For Accuracy, Confusion Matrix, Classification Report

def train1(metric, metric_name, y_train, y_pred_train):
  result = metric(y_train, y_pred_train)
  print(f"{metric_name}: {result}")


def test1(metric, metric_name, y_test, y_pred_test):
  result = metric(y_test, y_pred_test)
  print(f"{metric_name}: {result}")

In [107]:
# For Precision, Recall, F1 Score

def met_tr(metric, metric_name, y_train, y_pred_train, average = "weighted"):
  result = metric(y_train, y_pred_train, average=average)
  print(f"{metric_name}: {result}")

def met_te(metric, metric_name, y_test, y_pred_test, average = "weighted"):
  result = metric(y_test, y_pred_test, average=average)
  print(f"{metric_name}: {result}")

In [108]:
from sklearn.metrics import accuracy_score

train1(
    accuracy_score,
    "acc_score",
    y_train,
    y_pred_train
)

train1(
    accuracy_score,
    "acc_score",
    y_test,
    y_pred_test
)

acc_score: 0.8611802346249555
acc_score: 0.7960199004975125

In [109]:
from sklearn.metrics import confusion_matrix

train1(
    confusion_matrix,
    "cm_train",
    y_train,
    y_pred_train
)

train1(
    confusion_matrix,
    "cm_test",
    y_test,
    y_pred_test
)

cm_train: [[3848  274]
 [ 507  997]]
cm_test: [[931 111]
 [176 189]]

In [110]:
from sklearn.metrics import classification_report

train1(
    classification_report,
    "cr_train",
    y_train,
    y_pred_train
)

train1(
    classification_report,
    "cr_test",
    y_test,
    y_pred_test
)

cr_train:               precision    recall  f1-score   support

           0       0.88      0.93      0.91      4122
           1       0.78      0.66      0.72      1504

    accuracy                           0.86      5626
   macro avg       0.83      0.80      0.81      5626
weighted avg       0.86      0.86      0.86      5626

cr_test:               precision    recall  f1-score   support

           0       0.84      0.89      0.87      1042
           1       0.63      0.52      0.57       365

    accuracy                           0.80      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.79      0.80      0.79      1407

In [111]:
from sklearn.metrics import precision_score

met_tr(
    precision_score,
    "ps_train",
    y_train,
    y_pred_train,
    average = 'weighted'
)

met_te(
    precision_score,
    "ps_test",
    y_test,
    y_pred_test,
    average = 'weighted'
)

ps_train: 0.8570735216445804
ps_test: 0.7862716678576404

In [112]:
from sklearn.metrics import f1_score

met_tr(
    f1_score,
    "f1_train",
    y_train,
    y_pred_train,
    average = 'weighted'
)

met_te(
    f1_score,
    "f1_test",
    y_test,
    y_pred_test,
    average = 'weighted'
)

f1_train: 0.8572601154172793
f1_test: 0.7891358031911906

In [113]:
from sklearn.metrics import recall_score

met_tr(
    recall_score,
    "rs_train",
    y_train,
    y_pred_train,
    average = 'weighted'
)

met_te(
    recall_score,
    "rs_test",
    y_test,
    y_pred_test,
    average = 'weighted'
)

rs_train: 0.8611802346249555
rs_test: 0.7960199004975125

# Model Extraction

In [114]:
import pickle

with open("Model_churn.pkl", "wb") as f:
  pickle.dump(model_rf, f)

# Model Inputs

In [115]:
x_train.columns.to_list()

['Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'tenure',
 'Phone Service',
 'Multiple Lines',
 'Paperless Billing',
 'Monthly Charges',
 'Total Charges',
 'Internet Service_DSL',
 'Internet Service_Fiber optic',
 'Internet Service_No',
 'Online Security_No',
 'Online Security_No internet service',
 'Online Security_Yes',
 'Online Backup_No',
 'Online Backup_No internet service',
 'Online Backup_Yes',
 'Device Protection_No',
 'Device Protection_No internet service',
 'Device Protection_Yes',
 'Tech Support_No',
 'Tech Support_No internet service',
 'Tech Support_Yes',
 'Streaming TV_No',
 'Streaming TV_No internet service',
 'Streaming TV_Yes',
 'Streaming Movies_No',
 'Streaming Movies_No internet service',
 'Streaming Movies_Yes',
 'Contract_Month-to-month',
 'Contract_One year',
 'Contract_Two year',
 'Payment Method_Bank transfer (automatic)',
 'Payment Method_Credit card (automatic)',
 'Payment Method_Electronic check',
 'Payment Method_Mailed check']

In [116]:
x_train.Gender.unique()

array([0, 1])

In [117]:
x_train.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
5466,0,0,0,0,26,1,0,1,56.05,1553.20,1,0,0,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
5852,0,1,0,0,35,1,1,1,110.80,3836.30,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,1,0,1,0,0,0
4789,1,0,0,0,59,1,1,0,54.15,3116.15,1,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0
4129,1,0,0,0,57,0,0,1,39.30,2111.45,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0
3100,0,0,0,0,17,1,0,0,20.15,353.65,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1

In [118]:
x_train["Senior Citizen"].unique()

array([0, 1])

In [119]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Churn,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
1,0,0,1,0,1,0,0,1,29.85,29.85,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
2,1,0,0,0,34,1,0,0,56.95,1889.50,0,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
3,1,0,0,0,2,1,0,1,53.85,108.15,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
4,1,0,0,0,45,0,0,0,42.30,1840.75,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0,0

In [120]:
x_train.corr()

,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Paperless Billing,Monthly Charges,Total Charges,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Online Security_No,Online Security_No internet service,Online Security_Yes,Online Backup_No,Online Backup_No internet service,Online Backup_Yes,Device Protection_No,Device Protection_No internet service,Device Protection_Yes,Tech Support_No,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
Gender,1.000000,0.004949,-0.002484,0.000821,0.014640,-0.004077,0.006158,-0.013059,-0.012331,0.003168,-0.007367,-0.004516,0.013961,0.002526,0.013961,-0.015515,0.002949,0.013961,-0.015181,-0.006368,0.013961,-0.005444,0.002229,0.013961,-0.015138,-0.005659,0.013961,-0.006116,-0.006644,0.013961,-0.005127,-0.006750,0.007723,0.000500,-0.014109,0.004898,0.000611,0.008384
Senior Citizen,0.004949,1.000000,0.017058,-0.209783,0.014908,0.006674,0.143502,0.156067,0.218067,0.100526,-0.108392,0.254685,-0.181582,0.184589,-0.181582,-0.038850,0.086576,-0.181582,0.066879,0.088198,-0.181582,0.065192,0.203659,-0.181582,-0.059757,0.052856,-0.181582,0.100439,0.038844,-0.181582,0.114319,0.140653,-0.049687,-0.116862,-0.019562,-0.018458,0.171167,-0.156260
Partner,-0.002484,0.017058,1.000000,0.449766,0.373044,0.018959,0.148242,-0.015961,0.101620,0.316408,-0.009523,0.011353,-0.002670,-0.125371,-0.002670,0.141176,-0.131398,-0.002670,0.139642,-0.138525,-0.002670,0.147140,-0.107460,-0.002670,0.120970,-0.120261,-0.002670,0.123397,-0.111963,-0.002670,0.114396,-0.268946,0.077542,0.240168,0.111762,0.084199,-0.081047,-0.101057
Dependents,0.000821,-0.209783,0.449766,1.000000,0.154966,0.008083,-0.015568,-0.108573,-0.104990,0.061776,0.048943,-0.157883,0.133670,-0.183900,0.133670,0.081738,-0.132626,0.133670,0.022771,-0.124435,0.133670,0.014226,-0.163623,0.133670,0.059105,-0.100537,0.133670,-0.011861,-0.075819,0.133670,-0.036854,-0.215190,0.067044,0.187379,0.047875,0.054373,-0.141902,0.059989
tenure,0.014640,0.014908,0.373044,0.154966,1.000000,0.004096,0.332200,0.002169,0.249994,0.827699,0.023369,0.015260,-0.045411,-0.267434,-0.045411,0.337333,-0.302546,-0.045411,0.355555,-0.314143,-0.045411,0.367794,-0.259653,-0.045411,0.327680,-0.242559,-0.045411,0.282759,-0.253140,-0.045411,0.291868,-0.647981,0.203724,0.562475,0.245689,0.240602,-0.212222,-0.238168
Phone Service,-0.004077,0.006674,0.018959,0.008083,0.004096,1.000000,0.280562,0.013657,0.246880,0.111529,-0.449037,0.288295,0.171803,-0.063828,0.171803,-0.085882,-0.091578,0.171803,-0.053175,-0.075587,0.171803,-0.069899,-0.059794,0.171803,-0.090067,-0.119625,0.171803,-0.024907,-0.106878,0.171803,-0.037923,0.001220,0.000003,-0.001429,0.004469,-0.002217,-0.007525,0.006293
Multiple Lines,0.006158,0.143502,0.148242,-0.015568,0.332200,0.280562,1.000000,0.169814,0.503200,0.472775,-0.200072,0.373465,-0.218712,0.091840,-0.218712,0.097619,-0.013911,-0.218712,0.204078,-0.028290,-0.218712,0.219163,0.086955,-0.218712,0.102707,-0.083287,-0.218712,0.268999,-0.090261,-0.218712,0.274964,-0.079678,-0.013785,0.106327,0.072080,0.059571,0.081956,-0.222212
Paperless Billing,-0.013059,0.156067,-0.015961,-0.108573,0.002169,0.013657,0.169814,1.000000,0.348681,0.154233,-0.054716,0.320547,-0.323019,0.270404,-0.323019,-0.004964,0.148884,-0.323019,0.124330,0.168419,-0.323019,0.103924,0.232842,-0.323019,0.036501,0.053520,-0.323019,0.219474,0.063140,-0.323019,0.209333,0.167300,-0.038560,-0.158659,-0.020465,-0.013848,0.206294,-0.199642
Monthly Charges,-0.012331,0.218067,0.101620,-0.104990,0.249994,0.246880,0.503200,0.348681,1.000000,0.650665,-0.159187,0.785878,-0.762981,0.354787,-0.762981,0.302475,0.218705,-0.762981,0.432637,0.169398,-0.762981,0.484272,0.324913,-0.762981,0.334500,0.016994,-0.762981,0.628624,0.016809,-0.762981,0.626996,0.057835,-0.001410,-0.066254,0.041391,0.028917,0.267707,-0.372035
Total Charges,0.003168,0.100526,0.316408,0.061776,0.827699,0.111529,0.472775,0.154233,0.650665,1.000000,-0.045047,0.355696,-0.376555,-0.070102,-0.376555,0.420637,-0.166651,-0.376555,0.500501,-0.192495,-0.376555,0.527659,-0.082445,-0.376555,0.432932,-0.196144,-0.376555,0.516266,-0.205442,-0.376555,0.523525,-0.447047,0.167636,0.362137,0.188518,0.186743,-0.062587,-0.298261
Internet Service_DSL,-0.007367,-0.108392,-0.009523,0.048943,0.023369,-0.449037,-0.200072,-0.054716,-0.159187,-0.045047,1.000000,-0.642030,-0.382602,0.033847,-0.382602,0.311109,0.159770,-0.382602,0.164588,0.178794,-0.382602,0.144726,0.025553,-0.382602,0.319285,0.305500,-0.382602,0.016087,0.296488,-0.382602,0.025887,-0.071766,0.049682,0.036345,0.028609,0.048700,-0.099905,0.037015
Internet Service_Fiber optic,-0.004516,0.254685,0.011353,-0.157883,0.015260,0.288295,0.373465,0.320547,0.785878,0.355696,-0.642030,1.000000,-0.462703,0.401566,-0.462703,-0.022859,0.233020,-0.462703,0.157450,0.215045,-0.462703,0.176260,0.406908,-0.462703,-0.028662,0.062596,-0.462703,0.328552,0.066650,-0.462703,0.323688,0.244620,-0.082159,-0.207316,-0.025794,-0.050552,0.331608,-0.300107
Internet Service_No,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Online Security_No,0.002526,0.184589,-0.125371,-0.183900,-0.267434,-0.063828,0.091840,0.270404,0.354787,-0.070102,0.033847,0.401566,-0.523057,1.000000,-0.523057,-0.630144,0.383741,-0.523057,0.052229,0.373686,-0.523057,0.062720,0.467105,-0.523057,-0.040256,0.268063,-0.523057,0.172669,0.265459,-0.523057,0.175488,0.398712,-0.124201,-0.347203,-0.090648,-0.105506,0.332958,-0.183794
Online Security_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Online Security_Yes,-0.015515,-0.038850,0.141176,0.081738,0.337333,-0.085882,0.097619,-0.004964,0.302475,0.420637,0.311109,-0.022859,-0.332189,-0.630144,-0.332189,1.000000,-0.000539,-0.332189,0.288444,0.010895,-0.332189,0.276561,-0.043276,-0.332189,0.349430,0.093892,-0.332189,0.186570,0.091731,-0.332189,0.188435,-0.248280,0.099585,0.194919,0.102137,0.112563,-0.109653,-0.087090
Online Backup_No,0.002949,0.086576,-0.131398,-0.132626,-0.302546,-0.091578,-0.013911,0.148884,0.218705,-0.166651,0.159770,0.233020,-0.465551,0.383741,-0.465551,-0.000539,1.000000,-0.465551,-0.641678,0.352295,-0.465551,0.035236,0.388400,-0.465551,-0.005658,0.304635,-0.465551,0.087161,0.290358,-0.465551,0.102023,0.327692,-0.101948,-0.285483,-0.081966,-0.080685,0.230247,-0.100527
Online Backup_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Online Backup_Yes,-0.015181,0.066879,0.139642,0.022771,0.355555,-0.053175,0.204078,0.124330,0.432637,0.500501,0.164588,0.157450,-0.380054,0.052229,-0.380054,0.288444,-0.641678,-0.380054,1.000000,0.035551,-0.380054,0.292275,0.044630,-0.380054,0.295926,0.053121,-0.380054,0.268147,0.063246,-0.380054,0.257356,-0.158928,0.070531,0.118278,0.087396,0.080333,0.005562,-0.171260
Device Protection_No,-0.006368,0.088198,-0.138525,-0.124435,-0.314143,-0.075587,-0.028290,0.168419,0.169398,-0.192495,0.178794,0.215045,-0.465887,0.373686,-0.465887,0.010895,0.352295,-0.465887,0.035551,1.000000,-0.465887,-0.641636,0.422747,-0.465887,-0.043244,0.425348,-0.465887,-0.034147,0.429726,-0.465887,-0.037287,0.396725,-0.133977,-0.335525,-0.082336,-0.108027,0.235003,-0.078677
Device Protection_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Device Protection_Yes,-0.005444,0.065192,0.147140,0.014226,0.367794,-0.069899,0.219163,0.103924,0.484272,0.527659,0.144726,0.176260,-0.379754,0.062720,-0.379754,0.276561,0.035236,-0.379754,0.292275,-0.641636,-0.379754,1.000000,0.008696,-0.379754,0.335294,-0.073097,-0.379754,0.395030,-0.082472,-0.379754,0.403056,-0.231170,0.104044,0.170652,0.087811,0.108946,0.000570,-0.194137
Tech Support_No,0.002229,0.203659,-0.107460,-0.163623,-0.259653,-0.059794,0.086955,0.232842,0.324913,-0.082445,0.025553,0.406908,-0.519906,0.467105,-0.519906,-0.043276,0.388400,-0.519906,0.044630,0.422747,-0.519906,0.008696,1.000000,-0.519906,-0.630986,0.343401,-0.519906,0.094115,0.344561,-0.519906,0.093599,0.438350,-0.126336,-0.391493,-0.089195,-0.110115,0.339563,-0.188169
Tech Support_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Tech Support_Yes,-0.015138,-0.059757,0.120970,0.059105,0.327680,-0.090067,0.102707,0.036501,0.334500,0.432932,0.319285,-0.028662,-0.334649,-0.040256,-0.334649,0.349430,-0.005658,-0.334649,0.295926,-0.043244,-0.334649,0.335294,-0.630986,-0.334649,1.000000,0.010500,-0.334649,0.272651,0.004194,-0.334649,0.278189,-0.291211,0.101622,0.243151,0.100209,0.117289,-0.116580,-0.081999
Streaming TV_No,-0.005659,0.052856,-0.120261,-0.100537,-0.242559,-0.119625,-0.083287,0.053520,0.016994,-0.196144,0.305500,0.062596,-0.428684,0.268063,-0.428684,0.093892,0.304635,-0.428684,0.053121,0.425348,-0.428684,-0.073097,0.343401,-0.428684,0.010500,1.000000,-0.428684,-0.644470,0.532591,-0.428684,-0.171711,0.289758,-0.086043,-0.256361,-0.039884,-0.047539,0.099203,-0.026261
Streaming TV_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Streaming TV_Yes,-0.006116,0.100439,0.123397,-0.011861,0.282759,-0.024907,0.268999,0.219474,0.628624,0.516266,0.016087,0.328552,-0.414534,0.172669,-0.414534,0.186570,0.087161,-0.414534,0.268147,-0.034147,-0.414534,0.395030,0.094115,-0.414534,0.272651,-0.644470,-0.414534,1.000000,-0.178342,-0.414534,0.528429,-0.112609,0.051494,0.082352,0.041865,0.043985,0.140515,-0.243407
Streaming Movies_No,-0.006644,0.038844,-0.111963,-0.075819,-0.253140,-0.106878,-0.090261,0.063140,0.016809,-0.205442,0.296488,0.066650,-0.423149,0.265459,-0.423149,0.091731,0.290358,-0.423149,0.063246,0.429726,-0.423149,-0.082472,0.344561,-0.423149,0.004194,0.532591,-0.423149,-0.178342,1.000000,-0.423149,-0.644545,0.298854,-0.098490,-0.255083,-0.050939,-0.049825,0.100166,-0.014223
Streaming Movies_No internet service,0.013961,-0.181582,-0.002670,0.133670,-0.045411,0.171803,-0.218712,-0.323019,-0.762981,-0.376555,-0.382602,-0.462703,1.000000,-0.523057,1.000000,-0.332189,-0.465551,1.000000,-0.380054,-0.465887,1.000000,-0.379754,-0.519906,1.000000,-0.334649,-0.428684,1.000000,-0.414534,-0.423149,1.000000,-0.420005,-0.211805,0.041562,0.207807,-0.001997,0.004608,-0.284094,0.318854
Streaming Movies_Yes,-0.005127,0.114319,0.114396,-0.036854,0.291868,-0.037923,0.274964,0.209333,0.626996,0.523525,0.025887,0.323688,-0.420005,0.175488,-0.420005,0.188435,0.102023,-0.420005,0.257356,-0.037287,-0.420005,0.403056,0.093599,-0.420005,0.278189,-0.171711,-0.420005,0.528429,-0.644545,-0.420005,1.000000,-0.120607,0.063577,0.080139,0.052706,0.046017,0.139402,-0.254815
Contract_Month-to-month,-0.006750,0.140653,-0.268946,-0.215190,-0.647981,0.001220,-0.079678,0.167300,0.057835,-0.447047,-0.071766,0.244620,-0.211805,0.398712,-0.211805,-0.248280,0.327692,-0.211805,-0.158928,0.396725,-0.211805,-0.231170,0.438350,-0.211805,-0.291211,0.289758,-0.211805,-0.112609,0.298854,-0.211805,-0.120607,1.000000,-0.573082,-0.620499,-0.181799,-0.203567,0.325957,0.010210
Contract_One year,0.007723,-0.049687,0.077542,0.067044,0.203724,0.000003,-0.013785,-0.038560,-0.001410,0.167636,0.049682,-0.082159,0.041562,-0.124201,0.041562,0.099585,-0.101948,0.041562,0.070531,-0.133977,0.041562,0.104044,-0.126336,0.041562,0.101622,-0.086043,0.041562,0.051494,-0.098490,0.041562,0.063577,-0.573082,1.000000,-0.287059,0.048866,0.065146,-0.102414,0.003752
Contract_Two year,0.000500,-0.116862,0.240168,0.187379,0.562475,-0.001429,0.106327,-0.158659,-0.066254,0.362137,0.036345,-0.207316,0.207807,-0.347203,0.207807,0.194919,-0.285483,0.207807,0.118278,-0.335525,0.207807,0.170652,-0.391493,0.207807,0.243151,-0.256361,0.207807,0.082352,-0.255083,0.207807,0.080139,-0.620499,-0.287059,1.000000,0.165744,0.175610,-0.283008,-0.015525
Payment Method_Bank transfer (automatic),-0.014109,-0.019562,0.111762,0.047875,0.245689,0.004469,0.072080,-0.020465,0.041391,0.188518,0.028609,-0.025794,-0.001997,-0.090648,-0.001997,0.102137,-0.081966,-0.001997,0.087396,-0.082336,-0.001997,0.087811,-0.089195,-0.001997,0.100209,-0.039884,-0.001997,0.041865,-0.050939,-0.001997,0.052706,-0.181799,0.048866,0.165744,1.000000,-0.276315,-0.378052,-0.285145
Payment Method_Credit card (automatic),0.004898,-0.018458,0.084199,0.054373,0.240602,-0.002217,0.059571,-0.013848,0.028917,0.186743,0.048700,-0.050552,0.004608,-0.105506,0.004608,0.112563,-0.080685,0.004608,0.080333,-0.108027,0.004608,0.108946,-0.110115,0.004608,0.117289,-0.047539,0.004608,0.043985,-0.049825,0.004608,0.046017,-0.203567,0.065146,0.175610,-0.276315,1.000000,-0.376866,-0.284250
Payment Method_Electronic check,0.000611,0.171167,-0.081047,-0.141902,-0.212222,-0.007525,0.081956,0.206294,0.267707,-0.062587,-0.099905,0.331608,-0.284094,0.332958,-0.284094,-0.109653,0.230247,-0.284094,0.005562,0.235003,-0.284094,0.000570,0.339563,-0.284094,-0.116580,0.099203,-0.284094,0.140515,0.100166,-0.284094,0.139402,0.325957,-0.102414,-0.283008,-0.378052,-0.376866,1.000000,-0.388909
Payment Method_Mailed check,0.008384,-0.156260,-0.101057,0.059989,-0.238168,0.006293,-0.222212,-0.199642,-0.372035,-0.298261,0.037015,-0.300107,0.318854,-0.183794,0.318854,-0.087090,-0.100527,0.318854,-0.171260,-0.078677,0.318854,-0.194137,-0.188169,0.318854,-0.081999,-0.026261,0.318854,-0.243407,-0.014223,0.318854,-0.254815,0.010210,0.003752,-0.015525,-0.285145,-0.284250,-0.388909,1.000000

In [121]:
x_train["Dependents"].unique()

array([0, 1])

In [122]:
x_train["tenure"].unique()

array([26, 35, 59, 57, 17,  3, 71, 72, 58, 43, 37,  6, 41, 55,  8, 10,  2,
        4,  1,  9, 23, 31, 68, 25, 27,  5, 63, 13, 69,  7, 33, 15, 52, 60,
       54, 19, 18, 30, 40, 51, 29, 48, 22, 28, 49, 12, 44, 14, 34, 64, 39,
       67, 53, 16, 32, 61, 38, 50, 42, 11, 62, 45, 70, 66, 24, 36, 20, 65,
       56, 21, 46, 47])

In [123]:
x_train["tenure"].min()

1

In [124]:
x_train["tenure"].max()

72

In [125]:
x_train["tenure"].mean()

np.float64(32.34767152506221)

In [126]:
x_train["Multiple Lines"].unique()

array([0, 1])

In [127]:
x_train["Paperless Billing"].unique()

array([1, 0])

In [128]:
x_train["Monthly Charges"].unique()

array([ 56.05, 110.8 ,  54.15, ..., 114.6 ,  56.45, 114.5 ])

In [129]:
x_train["Monthly Charges"].min()

18.25

In [130]:
x_train["Monthly Charges"].max()

118.75

In [131]:
x_train["Monthly Charges"].mean()

np.float64(64.72708851759688)

In [132]:
x_train["Total Charges"].unique()

array([1553.2 , 3836.3 , 3116.15, ..., 4228.55,   39.3 , 5822.3 ])

In [133]:
x_train["Total Charges"].min()

18.85

In [134]:
x_train["Total Charges"].max()

8684.8